Repository MicrosoftDocs/windows-itpro-docs, pull requests merged in 2021-10, with the labels that each got.

#10000 Update windows-11.md
  windows/whats-new/windows-11.md
Labels: deployment

#9914 Making a change to Cryptomining policy on the 30th of Aug
  windows/security/threat-protection/intelligence/criteria.md
Labels: threat-protection

#10007 Correct spelling
  windows/whats-new/windows-11-prepare.md
Labels: deployment

#10008 Update defender-csp.md
  windows/client-management/mdm/defender-csp.md
Labels: antivirus, Microsoft submitter
