Repository MicrosoftDocs/windows-itpro-docs, pull requests merged in 2022-12, with the labels that each got.

#11015 Update volume-activation-management-tool.md
  windows/deployment/volume-activation/volume-activation-management-tool.md
Labels: Sign off

#10991 Update windows-10-subscription-activation.md
  windows/deployment/windows-10-subscription-activation.md
Labels: Sign off

#11044 added windows server 2022
  windows/security/information-protection/tpm/trusted-platform-module-overview.md
Labels: information protection

#11067 Update mcc-isp-faq.yml
  windows/deployment/do/mcc-isp-faq.yml
Labels: Microsoft submitter

#11074 Update waas-delivery-optimization-reference.md
  windows/deployment/do/waas-delivery-optimization-reference.md
Labels: Microsoft submitter

#11075 Update bitlocker-management-for-enterprises.md
  windows/security/information-protection/bitlocker/bitlocker-management-for-enterprises.md
Labels: Microsoft submitter

#11082 Update usmt-scanstate-syntax.md
  windows/deployment/usmt/usmt-scanstate-syntax.md
Labels: deployment

#11083 Update event-5140.md
  windows/security/threat-protection/auditing/event-4661.md
  windows/security/threat-protection/auditing/event-4691.md
  windows/security/threat-protection/auditing/event-5140.md
  windows/security/threat-protection/auditing/event-5145.md
Labels: threat-protection

#11100 Modify for convenience PIN
  windows/security/identity-protection/hello-for-business/hello-faq.yml
Labels: Microsoft submitter

#11103 Clarification of Settings Catalog options
  windows/deployment/update/wufb-reports-configuration-intune.md
Labels: Microsoft submitter
